# Generated by Django 6.0.5 on 2026-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquadApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=120, verbose_name='Название отряда')),
                ('commander_name', models.CharField(max_length=120, verbose_name='Имя командира')),
                ('contact', models.CharField(max_length=120, verbose_name='Discord или Telegram')),
                ('players_count', models.PositiveIntegerField(verbose_name='Количество игроков')),
                ('description', models.TextField(verbose_name='Описание отряда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на отряд',
                'verbose_name_plural': 'Заявки на отряды',
                'ordering': ['-created_at'],
            },
        ),
    ]
