# Generated by Django 6.0.5 on 2026-05-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadJoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=120, verbose_name='Отряд')),
                ('player_name', models.CharField(max_length=120, verbose_name='Игровой ник')),
                ('contact', models.CharField(max_length=120, verbose_name='Discord или Telegram')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('experience', models.CharField(max_length=160, verbose_name='Опыт в Arma Reforger')),
                ('message', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки на вступление',
                'ordering': ['-created_at'],
            },
        ),
    ]
