# Generated by Django 6.0.5 on 2026-05-10 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_squadjoinapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='squadapplication',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_squad_applications', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='squadjoinapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения'),
        ),
        migrations.AddField(
            model_name='squadjoinapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_squad_join_applications', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел'),
        ),
        migrations.AddField(
            model_name='squadjoinapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='squadjoinapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_join_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название отряда')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('players_count', models.PositiveIntegerField(default=1, verbose_name='Количество игроков')),
                ('recruitment_status', models.CharField(choices=[('open', 'Набор открыт'), ('closed', 'Набор закрыт')], default='open', max_length=16, verbose_name='Статус набора')),
                ('commander_name', models.CharField(blank=True, max_length=120, verbose_name='Командир')),
                ('specialization', models.TextField(blank=True, verbose_name='Специализация')),
                ('communication', models.CharField(blank=True, max_length=160, verbose_name='Связь')),
                ('schedule', models.CharField(blank=True, max_length=160, verbose_name='Расписание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_squads', to=settings.AUTH_USER_MODEL, verbose_name='Владелец отряда')),
            ],
            options={
                'verbose_name': 'Отряд',
                'verbose_name_plural': 'Отряды',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='squadjoinapplication',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_applications', to='main.squad', verbose_name='Отряд'),
        ),
        migrations.CreateModel(
            name='SquadMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='Имя игрока')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='Контакт')),
                ('role', models.CharField(choices=[('commander', 'Командир отряда'), ('deputy', 'Зам. командира'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.squad', verbose_name='Отряд')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник отряда',
                'verbose_name_plural': 'Участники отрядов',
                'ordering': ['squad', 'role', 'display_name'],
            },
        ),
    ]
