# Generated by Django 6.0.5 on 2026-05-12 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_approved_at_userprofile_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название события')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='URL')),
                ('date_label', models.CharField(max_length=60, verbose_name='Дата')),
                ('time_label', models.CharField(max_length=40, verbose_name='Время')),
                ('event_type', models.CharField(max_length=80, verbose_name='Тип события')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('mission_description', models.TextField(verbose_name='Описание миссии')),
                ('server_name', models.CharField(max_length=160, verbose_name='Название сервера')),
                ('server_ip', models.GenericIPAddressField(verbose_name='IP сервера')),
                ('server_port', models.PositiveIntegerField(verbose_name='Порт сервера')),
                ('max_solo_players', models.PositiveIntegerField(default=20, verbose_name='Слотов для одиночных игроков')),
                ('is_registration_open', models.BooleanField(default=True, verbose_name='Регистрация открыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSoloRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=120, verbose_name='Игровой ник')),
                ('contact', models.CharField(max_length=120, verbose_name='Discord или Telegram')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_registrations', to='main.event', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_solo_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация одиночного игрока',
                'verbose_name_plural': 'Регистрации одиночных игроков',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventSquadSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=120, verbose_name='Сторона / роль на миссии')),
                ('players_count', models.PositiveIntegerField(verbose_name='Количество игроков')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата слоттинга')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_squad_slots', to=settings.AUTH_USER_MODEL, verbose_name='Кто записал')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_slots', to='main.event', verbose_name='Событие')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_slots', to='main.squad', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Слоттинг отряда',
                'verbose_name_plural': 'Слоттинг отрядов',
                'ordering': ['squad__name'],
                'unique_together': {('event', 'squad')},
            },
        ),
    ]
