# Generated by Django 6.0.5 on 2026-05-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_eventsoloregistration_eventsquadslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlotDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название отделения')),
                ('total_slots', models.PositiveIntegerField(verbose_name='Количество слотов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_departments', to='main.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Отделение миссии',
                'verbose_name_plural': 'Отделения миссии',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventSlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(verbose_name='Номер слота')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата слоттинга')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_slot_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кто занял слот')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_slot_assignments', to='main.squad', verbose_name='Отряд')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.eventslotdepartment', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Занятый слот миссии',
                'verbose_name_plural': 'Занятые слоты миссии',
                'ordering': ['department', 'slot_number'],
                'unique_together': {('department', 'slot_number')},
            },
        ),
    ]
