# Generated by Django 6.0.5 on 2026-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventslotdepartment_eventslotassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_registration_open',
        ),
        migrations.AddField(
            model_name='event',
            name='solo_registration_open',
            field=models.BooleanField(default=False, verbose_name='Запись одиночных игроков открыта'),
        ),
        migrations.AddField(
            model_name='event',
            name='squad_slotting_open',
            field=models.BooleanField(default=False, verbose_name='Слоттинг отрядов открыт'),
        ),
    ]
