# Generated by Django 6.0.5 on 2026-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_event_is_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='password_visible_to_solo',
            field=models.BooleanField(default=False, verbose_name='Пароль виден одиночным игрокам'),
        ),
        migrations.AddField(
            model_name='event',
            name='password_visible_to_squads',
            field=models.BooleanField(default=True, verbose_name='Пароль виден отрядам'),
        ),
        migrations.AddField(
            model_name='event',
            name='server_password',
            field=models.CharField(blank=True, max_length=120, verbose_name='Пароль сервера'),
        ),
    ]
