# Generated by Django 6.0.5 on 2026-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_password_visible_to_solo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starts_at_unix',
            field=models.PositiveBigIntegerField(blank=True, help_text='Unix timestamp в секундах. На сайте дата и время будут показаны в часовом поясе пользователя.', null=True, verbose_name='Unix время события'),
        ),
    ]
